name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: windows-2022

    strategy:
      matrix:
        configuration: [ Release, Debug ]
        platform: [ x64 ]

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: 'true'

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet 5.2.0
        uses: nuget/setup-nuget@v2.0.0

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.28.x'

      - name: Generate Solution
        run: |
          rd /s /q _build
          mkdir _build
          cmake -B _build -S src -G "Visual Studio 17 2022"
        shell: cmd

      - name: Restore nuget packages
        run: msbuild '_build/DisplayRefreshRateController.sln' /p:configuration=${{ matrix.configuration }} /p:platform=${{ matrix.platform }} /t:restore

      - name: Build solution
        run: msbuild '_build/DisplayRefreshRateController.sln' /p:configuration=${{ matrix.configuration }} /p:platform=${{ matrix.platform }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.0
        with:
          name: DisplayRefreshRateController-${{ matrix.configuration }}-${{ matrix.platform }}
          path: ./_build/${{ matrix.configuration }}/DisplayRefreshRateController.exe
          if-no-files-found: error
