name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: windows-2022

    strategy:
      matrix:
        configuration: [ Release, Debug ]
        platform: [ x64 ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Use NuGet 5.2.0
        uses: nuget/setup-nuget@v1.2.0

      - name: Restore nuget packages
        run: msbuild 'src/DisplayRefreshRateController/DisplayRefreshRateController.sln' /p:configuration=${{ matrix.configuration }} /p:platform=${{ matrix.platform }} /t:restore

      - name: Build solution
        run: msbuild 'src/DisplayRefreshRateController/DisplayRefreshRateController.sln' /p:configuration=${{ matrix.configuration }} /p:platform=${{ matrix.platform }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DisplayRefreshRateController-${{ matrix.configuration }}-${{ matrix.platform }}
          path: ./src/DisplayRefreshRateController/${{ matrix.platform }}/${{ matrix.configuration }}/DisplayRefreshRateController.exe
          if-no-files-found: error
